version: "3.5"

services:
  buber-dinner:
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - sqlserver
    environment:
      ConnectionStrings__SqlConnection: "Server=sqlserver;Database=BuberDinner;User Id=SA;Password=Duyanh_6321;Encrypt=false;"
    ports:
      - "443:443"
      - "80:80"
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-preview-ubuntu-22.04
    restart: always
    container_name: sqlserver
    environment:
      MSSQL_SA_PASSWORD: "Duyanh_6321"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Evaluation"
    ports:
      - "1433:1433"
